### ISSUE TITLE
Can set breakpoints in  Xcode 15 , but unable to view variable content

### ISSUE THREAD

**Issue by MartinWong-H** [touchlab/xcode-kotlin#100]
i update to v.1.3.0 i can set breakpoint on xcode15 , but unable to show   variable content  and it can't print description .

and the variable panel is very stuck when it is opened.

![image](https://github.com/touchlab/xcode-kotlin/assets/11845233/88663d12-cfe0-4c5c-a546-620c0c6b44ce)

**Comment by hrach** [comment]
Same here. I just created a multiplatform template app in AS and then tried debugging it in Xcode 15. (I added sources as described in readme).

**Comment by SachsA** [comment]
<img width="1321" alt="Screenshot 2024-01-05 at 11 51 52" src="https://github.com/touchlab/xcode-kotlin/assets/27199365/e5faf749-a9e7-44dc-9d76-415556e03b0e">

I don't know if it's the same issue but I can also set some breakpoints but the Variables View tab is empty.
Also in Xcode 15 and plugin in 1.3.0.

**Comment by AdrianLeeElder** [comment]
I'm also having the same problem. However, I'm not sure it's because of Xcode 15. I installed Xcode 14.3.1 (using a suite of hacks to allow this on Sonoma). Other versions:

```
Kotlin compiler - 1.9.22
Compose = 1.6.0-dev1397
```

**Comment by chetandobariya** [comment]
same here.. I need to check variable content but unfortunately the same issue.. its shows as object pointer address value rather than actual value

**Comment by TadeasKriz** [comment]
Please give the version 2.0 a try and reopen this issue if you see the same issue.
