### ISSUE TITLE
Breakpoints became disable when we run the app

### ISSUE THREAD

**Issue by JJesus-WIT** [touchlab/xcode-kotlin#101]
## Summary

I have created a sample KMM framework project and have installed the plugin. What's happen is when I run the app on Xcode the breakpoints on KMM files, became disabled. 

Anyone know's what can be the issue?

## Details

Xcode: 15
Sample: KMM framework
Sample: [MyApplication.zip](https://github.com/touchlab/xcode-kotlin/files/13204759/MyApplication.zip)

## Reproduction

Run the Workspace app with the simulator

## Expected result

The breakpoints on the Greetings files should not became disabled, and should stop on the breakpoint

## Screenshots

<img width="570" alt="info command" src="https://github.com/touchlab/xcode-kotlin/assets/116637150/d1c07993-6478-49a5-b659-32262fef445a">
<img width="570" alt="info command" src="https://github.com/touchlab/xcode-kotlin/assets/116637150/04b741e7-5922-4523-9390-8d45d00ef095">

## Issue Labels

- [ X] has-reproduction

**Comment by TadeasKriz** [comment]
I've seen this happen when LLDB can't match the source file locations. Can you verify the KMP framework is compiled in Debug configuration?

**Comment by JJesus-WIT** [comment]
Note: I have this working on a production project, but for some reason, this new sample doesn't detect the breakpoint.

**Comment by kpgalligan** [comment]
It looks like you had "Copy items into destination group's folder (if needed)" checked (see [docs](https://github.com/touchlab/xcode-kotlin#plugin-usage). There's an extra local copy of the source files in your `iosApp` folder. Xcode needs to point at the actual source file. I moved those in my local copy and it works.

<img width="685" alt="Screenshot 2023-10-30 at 8 45 09 AM" src="https://github.com/touchlab/xcode-kotlin/assets/68384/cc4aa848-639c-42c2-9887-15785d0527ca">

**Comment by JJesus-WIT** [comment]
You are totally right.  Sorry for taking your time 

Thank you 💪

**Comment by JJesus-WIT** [comment]
true! i forgot to uncheck the "Copy items into destination group's folder (if needed)"

Thank you for your help! 💪
