### ISSUE TITLE
Support for multiproject Kotlin builds

### ISSUE THREAD

**Issue by egk2374** [touchlab/xcode-kotlin#102]
## Summary

I have a KMM project that has multiple subprojects. I want to add both subprojects to the "Kotlin Debug" group with the plugin. Build and debugging works perfectly when I add commonMain and iosMain from the first subproject, however when I add commonMain from the second subproject build always fails with the message "Multiple commands produce Library/Developer/Xcode/DerivedData/..../MyApp.app/commonMain

## Details

I have attempted this by adding all source sets directly in the Kotlin Debug group as well as making nested groups for each subproject and importing source sets inside those groups. The same result occurs with either approach.

## Reproduction

Create a KMM project with two subprojects, try to add commonMain source set from both projects into the xcode project.

## Expected result

I should be able to build the app with debug support for all Kotlin subprojects.

## Current state

I can build the app with debug support for no more than one Kotlin project.

## Issue Labels

- [ ] has-reproduction
- [ ] feature
- [ ] blocking
- [ ] good first issue

**Comment by TadeasKriz** [comment]
Hi, thanks for the report. Could you check if you're adding the `commonMain` to the bundle? You shouldn't do that and that'll fix it, because it will no longer copy the directory.

**Comment by TadeasKriz** [comment]
You can find the target membership by clicking on the `commonMain` in the project hierarchy and then look at the right panel:
 <img width="141" alt="image" src="https://github.com/touchlab/xcode-kotlin/assets/284197/55b35639-3ca0-485c-847d-016bca01339f">
