### ISSUE TITLE
Amend Sync paragraph with OS update case

### ISSUE THREAD

**Issue by maiow** [touchlab/xcode-kotlin#103]
## Summary

Documentation suggests to make sync in case of Xcode update only, need to mention also case of separate OS update here:
[(https://touchlab.co/xcodekotlin#sync)](https://touchlab.co/xcodekotlin#sync)

## Details

I was getting Xcode crashes after upgrading OS from Sonoma 1.14 to 14.1.1 (with same Xcode version), plugin sync helped.

## Expected result

Users will know in advance that any upgrade of Xcode or separate upgrade of OS requires plugin sync.

**Comment by TadeasKriz** [comment]
Hey @maiow, thanks for the report. The `sync` runs `fix-xcode15`, so you should be good to just run `xcode-kotlin fix-xcode15` when your Xcode 15 starts crashing. This is covered in the `Xcode 15 Support` paragraph:

> In case your Xcode starts crashing again, run xcode-kotlin fix-xcode15 (or xcode-kotlin sync). This will reapply the workaround and should make your Xcode work again.

With Xcode 15.1 that should hopefully go away, and you shouldn't need to run anything after a macOS update.

I'm closing this issue, but feel free to reopen it if you feel strongly about including this information in the Sync paragraph.
