### ISSUE TITLE
Support tvos, watchos and macos

### ISSUE THREAD

**Issue by ProVir** [touchlab/xcode-kotlin#105]
## Details

Support for other targets is required.
At the moment, there are no alternatives for debugging on tvos and watchos.
The only alternative in the form of a plug-in for the Android Studio also supports only iOS.

## Current state

Support only iOS

## Issue Labels

- [ ] has-reproduction
- [x] feature
- [ ] blocking
- [ ] good first issue

**Comment by TadeasKriz** [comment]
I just tested macOS and it works. I'd expect watchOS and tvOS should work too, could you test and reopen this issue if you're having problems? Thanks!
