### ISSUE TITLE
Xcode 15.4 debug kotlin unavailable for real devices

### ISSUE THREAD

**Issue by ElsonPeng** [touchlab/xcode-kotlin#112]
## Summary

I have installed the plugin with the intruction https://touchlab.co/xcodekotlin#-xcode-15-support-

## Details

I can add breakpoint when the program not running. But when xcode is run, the break point turn to unavailabe. It can be shown as the screenshots

## Screenshots

<img width="770" alt="image" src="https://github.com/touchlab/xcode-kotlin/assets/22700946/e05809a8-d69b-4f4f-a353-aad71c9cf020">
## Issue Labels

- [ ] has-reproduction
- [ ] feature
- [ ] blocking
- [ ] good first issue

**Comment by TadeasKriz** [comment]
Hi @ElsonPeng, could you check the following:

1. You're compiling the code you want to debug locally. Without source mapping you can't debug a published Kotlin framework (one that's built on a different machine).
2. You've built a debug configuration. Release configuration might not work due to optimizations and missing symbols.
3. Try putting a breakpoint in a non-Compose file. Since Compose does a lot of compile-time modifications, I wonder if that might be the cause.

Also, you mentioned "for real devices", does that mean it works fine on an iOS simulator?

**Comment by samhill303** [comment]
@ElsonPeng Please let us know if you are still having this issue and can follow up on Tadeas' questions.

**Comment by ElsonPeng** [comment]
@TadeasKriz @samhill303 YES, It works fine on an iOS simulator. Still have issue for real devices

**Comment by TadeasKriz** [comment]
@ElsonPeng Could you go through all my 3 steps and let me know answers to them?

**Comment by ElsonPeng** [comment]
> Hi @ElsonPeng, could you check the following:
> 
> 1. You're compiling the code you want to debug locally. Without source mapping you can't debug a published Kotlin framework (one that's built on a different machine).
> 2. You've built a debug configuration. Release configuration might not work due to optimizations and missing symbols.
> 3. Try putting a breakpoint in a non-Compose file. Since Compose does a lot of compile-time modifications, I wonder if that might be the cause.
> 
> Also, you mentioned "for real devices", does that mean it works fine on an iOS simulator?

1、Have source mapping
2、Debug configuration
3、I cannot understand non-Compose file mean？Files not involved in compilation?

**Comment by ElsonPeng** [comment]
> 2\. configuration
@TadeasKriz 
1、Have source mapping
2、Debug configuration
3、I cannot understand non-Compose file mean？Files not involved in compilation?

**Comment by TadeasKriz** [comment]
3. From the code you posted it seemed like Jetpack Compose code so I though that could be it. I'll retest debugging KaMPKit on a real device tomorrow. If I can't reproduce it, I'll need you to provide a minimal reproducer project.

**Comment by ElsonPeng** [comment]
> 3. From the code you posted it seemed like Jetpack Compose code so I though that could be it.
> 
> I'll retest debugging KaMPKit on a real device tomorrow. If I can't reproduce it, I'll need you to provide a minimal reproducer project.

OK, Thanks a lot. If your email address is [me@tadeaskriz.com]?

**Comment by mike-dydx** [comment]
i have the same issue, following!

**Comment by TadeasKriz** [comment]
I tried KaMPKit on my phone and it stopped where expected.

<img width="1860" alt="image" src="https://github.com/user-attachments/assets/3758b450-41ff-4a8e-9166-5818ef403be1">

Could you send a reproducer project I can try?

**Comment by TadeasKriz** [comment]
@mike-dydx @ElsonPeng ^^

**Comment by ElsonPeng** [comment]
I have resolved my problem. Thanks a lot. The reason is the compilation of product architecture.
