### ISSUE TITLE
Does not work with Xcode 11.2.1

### ISSUE THREAD

**Issue by below** [touchlab/xcode-kotlin#12]
While the DVTPlugInCompatibilityUUID seems to be included in the Plugin Plist, (`A74FBA51-FFEA-4409-B976-6FC3225A6F64`), Xcode does not seem to approve of that Plugin. Upon Clicking "Load Plugin", Xcode quits, and upon new launches, it will display the dialog to load the plugin, but then immediately quit without the plugin.

I am using [master@aa6bfba](https://github.com/touchlab/xcode-kotlin/commit/aa6bfbaeb0287745f8d0238ada18cfa68e9693d2)

**Comment by below** [comment]
Resolved after:
* Make sure Xcode is not running
* Delete Plugin
* Run `setup.sh`
* Start Xcode

**Comment by kpgalligan** [comment]
For the last few releases it seems like the plugin needs to be completely removed and reinstalled, which is frustrating, but will need to be added to the script.
