### ISSUE TITLE
PrintObject (po) statement doesn't work

### ISSUE THREAD

**Issue by romanandreyvich** [touchlab/xcode-kotlin#18]
I did everything described in Readme 
Now I'm able to use breakpoints but not able to use "po" statement or see an object state when code execution stopped at a breakpoint inside my common code.

Kotlin.ideplugin, Kotlin.xclangspec, Xcode.SourceCodeLanguage.Kotlin.plist are in the right place. Tried to reinstall the plugin but got the same issue.

Does it work as expected? I use Xcode 11.2 GM, macOs 10.14.4, KotlinNative 1.3.71

**Comment by Ricardo1980** [comment]
I have the same issue @romanandreyvich 
Did you fix it?
Thanks.

**Comment by raspu** [comment]
Same here, it was working for me for Xocde 11, but doesn't seem to work with Xcode 12

**Comment by yuzhiyunAtTencent** [comment]
Me too , "po" statement makes my XCode not responding

**Comment by yuzhiyunAtTencent** [comment]
> Me too , "po" statement makes my XCode not responding

xcode 12

**Comment by bvaillant-clgx** [comment]
same here on Xcode 12.

**Comment by kpgalligan** [comment]
People have been asking about this. We need to figure out how best to use cli access with po, then figure out how to hack the lldb script to support both.

**Comment by kpgalligan** [comment]
I think I finally know who's going to sort this out...

**Comment by shridharav** [comment]
Any updates on this?

**Comment by Haibo-Zhou** [comment]
Xcode 14.0.1, same, unable to PO. Guys, any update?

**Comment by TadeasKriz** [comment]
Hi, using `po` for simple variables in the frame should work with xcode-kotlin 2.0 and above. You can also use `fr v`.
