### ISSUE TITLE
Xcode 12.3 support

### ISSUE THREAD

**Issue by NotBrandon** [touchlab/xcode-kotlin#33]
It would seems as though the latest update to xcode, 12.3, has broken support for xcode-kotlin. I've tried removing and reinstalling the plugin. When booting xcode, I no longer get the prompt to load the plugin bundle.

**Comment by kpgalligan** [comment]
Will take a look, thanks.

**Comment by kpgalligan** [comment]
Added uuid for 12.3. Tried it locally. Seems to be OK.
