### ISSUE TITLE
Not working with Xcode 13.1

### ISSUE THREAD

**Issue by MattMur** [touchlab/xcode-kotlin#43]
I've recently upgraded from Xcode 12.3 to 13.1 and the debugging and syntax formatting is no longer working for me. I've tried re-running the setup script and re-importing my kotlin folders with no success. Has anyone else experienced this?

**Comment by hkawii** [comment]
Yes I got this issue too, I hope we can find any solution soon

**Comment by kpgalligan** [comment]
If this is still ongoing, somebody with 13.1 should re-send the UUID https://github.com/touchlab/xcode-kotlin#xcode-updates. That may be the issue. We're currently using the plugin on 13.2 without issue.
