### ISSUE TITLE
Add a CLI for installing and updating the plugin

### ISSUE THREAD

**Issue by TadeasKriz** [touchlab/xcode-kotlin#57]
We should add a CLI that would get installed using Homebrew. There's two ways we could make it work and we should decide which one is better.

## Bundled mode

In the bundled mode, the plugin files are included with the CLI binary when downloaded by Homebrew. Installing the `xcode-plugin` formula would automatically put the plugin to the right place. The CLI would then have a single purpose, to update the `DVTPlugInCompatibilityUUIDs` entry in the plugin's Info.plist file.

1. Running `xcode-plugin repair [xcode path,...]`
    a. Loads UUIDs of all currently installed Xcodes and those provided manually.
    b. Updates the `DVTPlugInCompatibilityUUIDs` entry in the installed plugin.
2. Running `xcode-plugin repair --only [xcode path,...]` 
    a. Loads UUIDs of only the Xcode paths provided manually.
    b. Updates the `DVTPlugInCompatibilityUUIDs` entry in the installed plugin.

When new changes to the plugin, users would run `brew upgrade xcode-kotlin` which would perform the same steps as the initial install, updating both the installed plugin and the CLI.

## Independent mode

In the independent mode, the plugin files live in a separate repository from the CLI. It's up to additional discussion whether the plugin would be installed during the CLI's installation by Homebrew.

The plugin would then have the following features:
1. Running `xcode-plugin install [version]` (`xcode-plugin update` would do the same)
    a. Downloads the latest plugin (or the version specified) from GitHub repository.
    b. Loads UUIDs of currently installed Xcodes and updates the `DVTPlugInCompatibilityUUIDs` plist entry.
    c. Copies the modified plugin to the plugins folder
2. Running `xcode-plugin repair [xcode path,...]`
    a. Loads UUIDs of currently installed Xcodes and those provided manually.
    b. Updates the `DVTPlugInCompatibilityUUIDs` entry in the installed plugin.
    c. Fails if the plugin is not installed yet.
4. Running `xcode-plugin repair [xcode path,...]`
    a. Loads UUIDs of only the Xcode paths provided manually.
    b. Updates the `DVTPlugInCompatibilityUUIDs` entry in the installed plugin.
    c. Fails if the plugin is not installed yet.

**Comment by TadeasKriz** [comment]
Personally I would argue for the "Bundled mode" as the updating is done by Homebrew's solid logic, without requiring us to write it from scratch.

**Comment by kpgalligan** [comment]
Read this

**Comment by kpgalligan** [comment]
I vote bundled. I'd like to make sure that the automatic UUID process makes sense, but otherwise I think bundled is good. We won't need to update all that much if we can handle the Xcode changes locally.

**Comment by kpgalligan** [comment]
Next step I think it to figure out how we'll build the CLI (Kotlin, something else?), then figure out who gets to do it.
