### ISSUE TITLE
Xcode update causes crash

### ISSUE THREAD

**Issue by pmodernme** [touchlab/xcode-kotlin#58]
Xcode 13.3.1 (13E500a) crashes on startup M1 Max MBP running macOS 12.3.1.

Attempted simply rerunning `./setup.sh` to reinstall, but it did not solve the issue.

Solution was to remove the plugin from `~/Library/Developer/Xcode/Plug-ins` and the spec from `~/Library/Developer/Xcode/Specifications`. Xcode then opened successfully. Ran xcode-kotlin's `setup.sh` to reinstall. Xcode opens successfully.

**Comment by filimo** [comment]
![3232d781-2c40-4802-8a68-42a2c6e50b9d](https://user-images.githubusercontent.com/327296/163125816-0921e90d-e9d1-48bc-b958-910984d28911.jpg)

**Comment by kpgalligan** [comment]
We're doing a major rewrite of the install tool. I'm going to keep this active to review when the new version settles.

**Comment by TadeasKriz** [comment]
Closing as stale.
