### ISSUE TITLE
xcode-kotlin install  crash (XCode 13.4)

### ISSUE THREAD

**Issue by joreilly** [touchlab/xcode-kotlin#85]
I ran `brew install xcode-kotlin` first and then when I run `xcode-kotlin install` I get following (crash report hopefully uploaded short while ago) .  This is M1 device fwiw.    Currently have Xcode 13.4 installed.

```
Installing 1.2.0.
xcode-kotlin has crashed, do you want to upload the crash report to Touchlab? y/n: y
Uploading crash report.
Upload successful
```

**Comment by kpgalligan** [comment]
Thanks! That is interesting. We tested on M1 and Intel, but probably not that Xcode version. It should work regardless of version, but the CLI is trying to do a lot more than the old setup script. Will check it out...

**Comment by GuilhE** [comment]
Same here with **M1 Pro** and **XCode 13.4 (13F17a)**:

```
➜  ~ brew install xcode-kotlin
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
dbml-cli     gcc@12       goctl        sdl2_sound   sftpgo       ttmath
==> Updated Formulae
Updated 72 formulae.
==> Updated Casks
Updated 60 casks.

==> Downloading https://ghcr.io/v2/homebrew/core/xcode-kotlin/manifests/1.2.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/xcode-kotlin/blobs/sha256:e30d4
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Pouring xcode-kotlin--1.2.0.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/xcode-kotlin/1.2.0: 12 files, 2.7MB
==> Running `brew cleanup xcode-kotlin`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜  ~ xcode-kotlin install
Installing 1.2.0.
xcode-kotlin has crashed, do you want to upload the crash report to Touchlab? y/n: y
Uploading crash report.
Upload successful
```

**Comment by TadeasKriz** [comment]
Thanks for the reports! It's embarrassing, I didn't make the CLI create the directory structure needed before copying the plugin (thinking it was already created by Xcode). I've just submitted an update to Homebrew (version 1.2.1), but it'll take a while to release.

In the meantime, running the following two commands before `xcode-kotlin install` should workaround the crash:
```
mkdir -p ~/Library/Developer/Xcode/Plug-ins
mkdir -p ~/Library/Developer/Xcode/Specifications
```

**Comment by GuilhE** [comment]
> Thanks for the reports! It's embarrassing, I didn't make the CLI create the directory structure needed before copying the plugin (thinking it was already created by Xcode). I've just submitted an update to Homebrew (version 1.2.1), but it'll take a while to release.
> 
> In the meantime, running the following two commands before `xcode-kotlin install` should workaround the crash:
> 
> ```
> mkdir -p ~/Library/Developer/Xcode/Plug-ins
> mkdir -p ~/Library/Developer/Xcode/Specifications
> ```

It works and this plugin is fantastic! Thanks 🙇🏼

**Comment by kpgalligan** [comment]
Update posted and merged to homebrew. Try again!
