### ISSUE TITLE
Step into Kotlin from Swift/Objc

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/xcode-kotlin#87]
Explore being able to step into Kotlin from calling code (Swift/Objc). I'm pretty sure this isn't possible, but it's something we should explore.

See Slack for some context: https://kotlinlang.slack.com/archives/C3PQML5NU/p1654805821671169

**Comment by SimekVlad** [comment]
It is really not possible to step into kotlin source code from swiftui ? It is necesarry to step into compiled objectiveC file?
