### ISSUE TITLE
Can set breakpoints in release build in Xcode, but debug build doesn't see Kotlin files at all

### ISSUE THREAD

**Issue by bodritto** [touchlab/xcode-kotlin#88]
Hi!

I've installed plugin from CLI, added iosMain and commonMain as it's suggested in video tutorial

I observe crashes in my release build in iOS, and for some reason I see kotlin files in stack trace, and I can set breakpoints

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/2625738/183092400-6cd10325-90c2-4875-b076-42e3a3ca16ce.png">

Debug build doesn't allow to set breakpoints at all.

*Output of xcode-kotlin info*:

`Installed plugin version:	1.2.1
Bundled plugin version:		1.2.1

Language spec installed: Yes
LLDB init installed: Yes
LLDB Xcode init sources main LLDB init: No

Installed Xcode versions:
✔	Xcode 13.2.1 (13C90b)	7A3A18B7-4C08-46F0-A96A-AB686D315DF0	/Applications/Xcode.app

✔ - plugin is compatible, x - plugin is not compatible
Run 'xcode-kotlin sync' to add compatibility for all listed Xcode versions.`

I've seen how files in filetree look like on the video (with Koltin icon), it's not like that for me:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/2625738/183089760-4fd96aa2-927b-42c0-928a-bdbc5eaa81ef.png">

I've checked KaMPKitiOS project and it's working fine.

This project is big, its main contributor has left and I need to make some support fixes for it. Also I'm not very experienced mobile developer but I have been writing some backend/web development for several years.

Thank you for any help!

**Comment by feiliu123** [comment]
I have encountered the same problem, Xcode 14.2,mac M1, there is further progress on this problem, has it been solved? If possible, could you share your experience? Thanks a million

**Comment by kpgalligan** [comment]
So far, all of these issues are due to incorrect configuration. Debug builds can definitely be debugged, when the IDE is configured correctly.

Please open a new issue, and explain how your build is set up, and how you've added your Kotlin files to the Xcode project.
