### ISSUE TITLE
Kotlin 1.9.0-RC has a significantly updated lldb script

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/xcode-kotlin#94]
## Summary

We use the lldb script that ships with Kotlin, which hasn't changed in many versions. It has changed with 1.9 fairly significantly.

## Details

We use the same lldb script as Kotlin. In the past, we've had a lightly modified script, for optimizations. I'm not sure if our last script was 100% stock or not (I think it was, but it has been some time). We need to take the script from 1.9.0, put it in the plugin, and test that building with 1.9.0 works for debugging.

Then, assuming that works, we should get a sense of performance. If the debugging works OK, we can just move forward, and maybe add another task to look into performance. If it's bad, or doesn't work at all, we'll need to dig deeper.

After everything works, we'll need to release a new version of the install tool. We don't currently support multiple Kotlin versions with the tool, mostly because the lldb script hasn't changed in a long time. We'll probably need to have the "install" process somehow be able to distinguish versions. Should discuss a design of this after we test that 1.9 works.

**Comment by kpgalligan** [comment]
Context on what triggered this issue: https://kotlinlang.slack.com/archives/CTJB58X7X/p1687275483250989

**Comment by russhwolf** [comment]
This is the only commit where the script has changed since 2020. Appears to also be the only diff from what we have currently in the plugin.

https://github.com/JetBrains/kotlin/commit/55632f5df2f830cb2a2cdb9d77824ce32eddf6c9#diff-a5432bc7a805aed981d9fb0b43349c5ca8ed028e9a34e2e6cc9c5c1e46795776

**Comment by slipdef** [comment]
So I'm not clear does the plugin support 1.9?

**Comment by TadeasKriz** [comment]
Yes, the plugin supports Kotlin 1.9 and also Kotlin 2.0.
