### ISSUE TITLE
Xcode 15 beta has issues

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/xcode-kotlin#95]
Various reports have come in that Xcode 15 does not work. Xcode 15 is still in beta, so this may not be an issue, but we are always at the mercy of Apple and what they plan to shut down as far as Xcode extendability. We should try this out and see if we can sort out issues.

**Comment by mbuchetics** [comment]
any news here?

**Comment by kpgalligan** [comment]
Not yet. It's on the radar for sure.

**Comment by TadeasKriz** [comment]
I've been looking into it and so far it seems to be a bug in Xcode itself. It happens with other 3rd party plugins as well. I also tried to extract Apple's plugin out of the Xcode.app bundle and it's crashing too.

I've filed a radar/feedback to Apple about this issue. Please go ahead and dupe it: https://openradar.appspot.com/radar?id=5500625966071808 Thanks!

**Comment by MatyasKriz** [comment]
A bit unrelated, but if you're forced to use Xcode 15 for iOS 17 device support, there's a workaround for adding iOS 17 device support into Xcode 14 and keep plugin functionality – https://developer.apple.com/forums/thread/730947?answerId=758061022#758061022

You need to install and setup Xcode 15 beforehand, but I've just tested it and AFAICT it works just the same. 😁

**Comment by TadeasKriz** [comment]
We've released a new version of Xcode Kotlin. It's available through Homebrew and contains an automated workaround for this issue, check it out.
