### ISSUE TITLE
Build failure against gradle 8.3

### ISSUE THREAD

**Issue by chenrui333** [touchlab/xcode-kotlin#98]
## Summary

👋 while building the bottle for macOS sonoma, we found that it does not build against gradle 8.3 (I can reproduce in ventura arm as well)

```
* What went wrong:
There is no feature named VERSION_CATALOGS
```

full log in here, https://github.com/Homebrew/homebrew-core/actions/runs/6221266453/job/16882886286

## Reproduction

`HOMEBREW_NO_INSTALL_FROM_API=1 brew install -s xcode-kotlin`

## Screenshots

<img width="250" alt="fix in action" src="https://media.makeameme.org/created/yes-it-works.jpg">

## Issue Labels

- [ ] has-reproduction
- [ ] feature
- [ ] blocking
- [ ] good first issue

**Comment by TadeasKriz** [comment]
Hey, thanks for reporting this. I've updated the version of Gradle to 8.4 along with releasing a new version 1.3.0 to homebrew-core.
